### ISSUE TITLE
CLI: パイプ読み取り

### ISSUE THREAD

**Issue by 844196** [844196/n_cipher#5]
<blockquote class="twitter-tweet" lang="ja"><p lang="ja" dir="ltr">これはstdinから読めたらべんりそう</p>&mdash; sasairc_2 (@sasairc_2) <a href="https://twitter.com/sasairc_2/status/652457179870466048">2015, 10月 9</a></blockquote>

<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>

**Comment by sasairc** [comment]
@844196 
:+1:

**Comment by 844196** [comment]
@sasairc 
![2015-09-19_17-48-44](https://cloud.githubusercontent.com/assets/4990822/10394079/a7d4b184-6ecf-11e5-82e6-b3c5db829d31.png)
